----------------------------------English---------------------------------------
--------------------------------------------------------------------------------
local Language = GetLocale()

if (Language=="enGB" or Language=="enUS") then 

LLPvpState_Locals = {};

LLPvpState_Locals = {

----Global
["Alliance"] = "Alliance",
["Horde"] = "Horde",

----Zone
["Arathi Basin"] = "Arathi Basin",
["Warsong Gulch"] = "Warsong Gulch",
["Isle of Conquest"] = "Isle of Conquest",
["Eye of the Storm"] = "Eye of the Storm",
["Strand of the Ancients"] = "Strand of the Ancients",
["Alterac Valley"] = "Alterac Valley",
["Battle for Gilneas"] = "The Battle for Gilneas",
["Twin Peaks"] = "Twin Peaks",
["Wintergrasp"] = "Wintergrasp",
["Tol Barad"] = "Tol Barad",
["Tol Barad Peninsula"] = "Tol Barad Peninsula",
["Terokkar Forest"] = "Terokkar Forest",
["Hellfire Peninsula"] = "Hellfire Peninsula",
["Nagrand"] = "Nagrand",
["Eastern Plaguelands"] = "Eastern Plaguelands",

----Wintergrasp
["Horde Controlled"] = "Horde Controlled",
["Alliance Controlled"] = "Alliance Controlled",
["Timer unavailable"] = "unavailable",
["Battle in progress"] = "Battle in progress",
["Wgrasp FortTower"] = "Wintergrasp Fortress Tower",
["Wgrasp FortDoor"] = "Wintergrasp Fortress Door",
["Wgrasp FortWall"] = "Wintergrasp Fortress Wall",
["Wgrasp Wall"] = "Wintergrasp Wall",
["Wgrasp FortGate"] = "Wintergrasp Fortress Gate",
["GobWorkshop"] = "Goblin Workshop",
["Shadow tower"] = "Shadowsight Tower",
["WE tower"] = "Winter's Edge Tower",
["FW tower"] = "Flamewatch Tower",

--STRAND OF ANCIENTS
["Gate Blue"] = "Gate of the Blue Sapphire",
["Gate Green"] = "Gate of the Green Emerald",
["Gate Purple"] = "Gate of the Purple Amethyst",
["Gate Red"] = "Gate of the Red Sun",
["Gate Yellow"] = "Gate of the Yellow Moon",
["reliq chamber"] = "Chamber of Ancient Relics",  

----Battleground
["Preparation"] = "Preparation",
["Alterac Valley START"] = "Alterac Valley begins in :",
["Arathi Basin START"] = "Arathi Basin begins in :",
["Eye of the Storm START"] = "Eye of the Storm begins in :",
["Isle of Conquest START"] = "Isle of Conquest begins in :",
["Strand of the Ancients START"] = "Strand of the Ancients begins in :",
["Warsong Gulch START"] = "Warsong Gulch begins in :",
["Gilneas START"] = "Gilneas Battle begins in :",
["Twin START"] = "Twin Peaks begins in :",
["Battle Begins"] = "Battle begins in :",
["1 minute"] = "1 minute",
["60 second"] = "60 second", 
["30 second"] = "30 second",
["15 second"] = "15 second",

----Warsong Gulch
["Alliance take flag"] = "The Horde flag was picked up by ",
["Horde take flag"] = "The Alliance Flag was picked up by ",
["Alliance loose flag"] = "The Horde flag was dropped by ", 
["Alliance capture"] = "captured the Horde flag",
["Alliance return"] = "The Alliance Flag was returned",
["Horde return"] = "The Horde flag was returned",
["Horde loose flag"] = "The Alliance Flag was dropped by ", 
["Horde capture"] = "captured the Alliance flag",
["Alliance Flag"] = "Alliance Flag",
["Horde Flag"] = "Horde Flag",
["Horde Flag 2"] = "Horde Flag",

----Arathi Basin
["Resources"] = "Resources",
["stable"] = "stables",
["stables"] = "Stables",
["farm claimed"] = "claims the farm",
["farm assaulted"] = "has assaulted the farm",
["blacksmith claimed"] = "claims the blacksmith",
["blacksmith assaulted"] = "has assaulted the blacksmith",
["mine claimed"] = "claims the mine",
["mine assaulted"] = "has assaulted the mine",
["stables claimed"] = "claims",
["stables assaulted"] = "has assaulted the stables",
["lumber mill claimed"] = "claims the lumber mill",
["lumber mill assaulted"] = "has assaulted the lumber mill",
["farm captured"] = "has taken the farm",
["blacksmith captured"] = "has taken the blacksmith", 
["lumber mill captured"] = "has taken the lumber mill", 
["mine captured"] = "has taken the mine", 
["stables captured"] = "has taken the stables",
["farm"] = "Farm",
["blacks"] = "Blacksmith",
["lumb"] = "Lumber Mill",
["mine"] = "Mine",
["stableN"] = "Stables",  

----Isle Of Conquest
["Reinforcements"] = "Reinforcements",
["quarry assaulted"] = "has assaulted the quarry",
["hangar assaulted"] = "has assaulted the hangar",
["docks assaulted"] = "has assaulted the docks",
["workshop assaulted"] = "has assaulted the workshop",
["refinery assaulted"] = "has assaulted the oil refinery",
["horde keep assaulted"] = "has assaulted the horde keep",
["alliance keep assaulted"] = "has assaulted the alliance keep",
["quarry captured"] = "has taken the quarry",
["hangar captured"] = "has taken the hangar",
["docks captured"] = "has taken the docks",
["workshop captured"] = "has taken the workshop",
["refinery captured"] = "has taken the oil refinery",
["horde keep captured"] = "has taken the horde keep",
["alliance keep captured"] = "has taken the alliance keep",
["alliance gate"] = "gate of the Alliance keep",
["horde gate"] = "gate of the Horde keep",
["quarry"] = "Quarry",
["hangar"] = "Hangar",
["docks"] = "Docks",
["workshop"] = "Workshop",
["refinery"] = "Refinery",
["hordekeep"] = "Horde keep",
["alliancekeep"] = "Alliance keep",
["alliancesiege"] = "S.engine : alliance",
["hordesiege"] = "S.engine : horde",
["gate"] = "gate",
["SiegeEngine"] = "Siege Engine",
["Alliance Gate"] = "Alliance Gate",
["Horde Gate"] = "Horde Gate",
["horde door down"] = "Horde gate destroyed!",
["alliance door down"] = "Alliance gate destroyed!",

----EyeOfTheStorm
["Victory Points"] = "Victory Points",
["has taken the flag"] = "has taken the flag",
["have captured the flag"] = "have captured the flag",
["has been dropped"] = "has been dropped",
["EOTS Flag"] = "Netherstorm Flag",
["draenei captured"] = "has taken control of the Draenei Ruins",
["mage captured"] = "has taken control of the Mage Tower",
["eds captured"] = "has taken control of the Blood Elf Tower",
["felreaver captured"] = "has taken control of the Fel Reaver Ruins",
["draenei lost"] = "has lost control of the Draenei Ruins",
["mage lost"] = "has lost control of the Mage Tower",
["eds lost"] = "has lost control of the Blood Elf Tower",
["felreaver lost"] = "has lost control of the Fel Reaver Ruins",
["Draenei ruins"] = "Draenei Ruins",
["fel reaver"] = "Fel Reaver Ruins",
["eds"] = "Blood Elf Tower",
["mage"] = "Mage Tower",

----Alterac Valley
["Reinforcements"] = "Reinforcements",
["herald"] = "Herald",
["Ndun"] = "DB North",
["Sdun"] = "DB south",
["icewingt"] = "Icewing Bunker",
["stoneheartht"] = "Stonehearth",
["icebloodt"] = "Iceblood Tower",
["towerpoint"] = "Tower Point",
["eastfrost"] = "East frostwolf",
["westfrost"] = "West Frostwolf",
["NDun defended"] = "Dun Baldar North Bunker was taken",
["NDun assaulted"] = "Dun Baldar North Bunker is under attack" ,
["NDun destroyed"] = "Dun Baldar North Bunker was destroyed",
["SDun defended"] = "Dun Baldar South Bunker was taken",
["SDun assaulted"] = "Dun Baldar South Bunker is under attack",
["SDun destroyed"] = "Dun Baldar South Bunker was destroyed",
["IcewingT defended"] = "Icewing Bunker was taken",
["IcewingT assaulted"] = "Icewing Bunker is under attack" ,
["IcewingT destroyed"] = "Icewing Bunker was destroyed",
["StonehearthT defended"] = "Stonehearth Bunker was taken",
["StonehearthT assaulted"] = "Stonehearth Bunker is under attack" ,
["StonehearthT destroyed"] = "Stonehearth Bunker was destroyed",
["IcebloodT defended"] = "Iceblood Tower",
["takenice"] = "was taken",
["IcebloodT assaulted"] = "Iceblood Tower",
["assaultedice"] = "is under attack",
["IcebloodT destroyed"] = "Iceblood Tower was destroyed",
["TowerPoint defended"] = "Tower Point was taken",
["TowerPoint assaulted"] = "Tower Point is under attack",
["TowerPoint destroyed"] = "Tower Point was destroyed",
["EastFrostT defended"] = "East Frostwolf Tower was taken",
["EastFrostT assaulted"] = "East Frostwolf Tower is under attack",
["EastFrostT destroyed"] = "East Frostwolf Tower was destroyed",
["WestFrostT defended"] = "West Frostwolf Tower was taken",
["WestFrostT assaulted"] = "West Frostwolf Tower is under attack",
["WestFrostT destroyed"] = "West Frostwolf Tower was destroyed",
["Stormpike assaulted"] = "Stormpike Graveyard is under attack", 
["Stormpike captured"] = "Stormpike Graveyard was taken by",
["stonehearth assaulted"] = "Stonehearth Graveyard is under attack",
["stonehearth captured"] = "Stonehearth Graveyard was taken by",
["tower"] = "Tower",
["graveyard"] = "Graveyard",
--chat msg bg
["Snowfall assaulted2"] = "claims the Snowfall graveyard",
["Iceblood assaulted"] = "Iceblood Graveyard",
["Icebloodassault"] = "under attack",
["Icebloodtaken"] = "was taken",
["Stormpike Aid Station assaulted"] = "Stormpike Aid Station is under attack",
["Stormpike Aid Station captured"] = "Stormpike Aid Station was taken",
["Frostwolf assaulted"] = "Frostwolf Graveyard",
["FrostwolfRH assaulted"] = "Relief",
["Snowfall assaultedi"] = "Snowfall Graveyard",
["Snowfall assaultedj"] = "Snowfall Graveyard",
["Stormpike Aid Station"] = "S. Aid Station",
["Stormpike grave"] = "Storm. Grave.",
["stonehearth grave"] = "Stone. Grave.",
["Snowfall grave"] = "Snowfall Grave.",
["Iceblood grave"] = "Iceblood Grave.",
["Frostwolf grave"] = "Frostwolf Grave.",
["Frostwolf Relief Hut"] = "F. Relief Hut",
["irondeepmine captured"] = "Irondeep",
["coldtoothmine captured"] = "Coldtooth",
["irondeep"] = "Irondeep",
["coldtooth"] = "Coldtooth",

----Gilneas
--["Resources"] = "Resources",
["Waterworks"] = "Waterworks",
["mines"] = "Mines",
["lighthouse"] = "Lighthouse",
["mines claimed"] = "claims the mines",
["mines assaulted"] = "has assaulted the mines",
["waterworks claimed"] = "claims the waterworks",
["waterworks assaulted"] = "has assaulted the waterworks",
["light claimed"] = "claims the lighthouse",
["light assaulted"] = "has assaulted the lighthouse",
["mines captured"] = "has taken the mines",
["waterworks captured"] = "has taken the waterworks", 
["light captured"] = "has taken the lighthouse", 

----Tol Barad
["Control Alliance"] = "Alliance Controlled",
["Control Horde"] =  "Horde Controlled",
["Horde Attack"] = "Horde is Attacking",
["Alliance Attack"] = "Alliance is Attacking",
["warden captured"] = "has taken Warden",
["warden captured2"] = "has gained control of Warden",
["warden lost"] = "has lost Warden",
["warden lost2"] = "has lost control of Warden",
["slagworks captured"] = "has taken the Slagworks",
["slagworks captured2"] = "has gained control of the Slagworks",
["slagworks lost"] = "has lost control of the Slagworks",
["slagworks lost2"] = "has lost the Slagworks",
["ironclad captured"] = "has taken the Ironclad Garrison",
["ironclad captured2"] = "has gained control of the Ironclad Garrison",
["ironclad lost"] = "has lost control of the Ironclad",
["ironclad lost2"] = "has lost the Ironclad",

----Alliance/Horde
["Alliance"] = "Alliance",



};

end 

